#!/usr/bin/env python3
# ============================================================
#  yvcf2diyabc_fixed.py
#  将 Y 染色体 VCF ➜ DIYABC-RF IndSeq SNP TXT
#  —— 所有路径和参数集中在 USER CONFIG 区域 —— 
# ============================================================

import pandas as pd
from cyvcf2 import VCF
from pathlib import Path
import sys

# ========= USER CONFIG ======================================
# ① Y-SNP VCF（可压缩 .vcf.gz）
vcf_path   = r"/mnt/d/Sex_biased_project/7049_sexbi.indel.lowq.het.dp2.mis0.05.mM2.format.vcf.gz"

# ② 样本与族群对照表（两列：SampleID  PopulationID）
pop_table  = r"/mnt/f/OneDrive/科研/4_代码/DIYABC-RF/conf/1_random_sampled.txt" # 无表头

# ③ 生成的 DIYABC 输入文件
out_txt    = r"/mnt/f/OneDrive/科研/4_代码/DIYABC-RF/output/TB.snp" # 后缀必须是.snp，提取的多态位点

# ④ 标题行参数
sex_ratio  = "<NM=1.0NF>"       # 雄性/雌性比，=1 表示 1:1
maf_tag    = "<MAF=hudson>"     # 或例如 "<MAF=0.05>"
# ============================================================

# ---------- 1. 读取族群表 ----------
pop_df = pd.read_csv(pop_table, sep=r"\s+", header=None, names=["ID", "POP"])
target_samples = pop_df.ID.tolist()
pop_map = dict(zip(pop_df.ID, pop_df.POP))

print(f"[INFO] 目标样本 {len(target_samples)} 个，将从 VCF 中提取…")

# ---------- 2. 打开 VCF，仅保留目标样本 ----------
vcf = VCF(vcf_path)
vcf.set_samples(target_samples)
samples = vcf.samples               # 已按 target 顺序重排

# ---------- 3. 遍历位点，提取 Y-SNP ----------
geno_dict = {s: [] for s in samples}
n_loci = 0

for var in vcf:
    if var.CHROM not in ("Y", "chrY"):
        continue
    if len(var.ALT) != 1:           # 仅两等位（1个REF + 1个ALT）
        continue

    # 判断在目标样本中是否多态（REF 与 ALT 至少各出现一次）
    alleles = set(gt[0] for gt in var.genotypes if gt[0] != -1)
    if len(alleles) < 2:
        continue

    n_loci += 1
    for idx, gt in enumerate(var.genotypes):
        a1 = gt[0]  # 获取第一个（也是唯一的）等位基因
        g = 9                       # 缺失
        if a1 != -1:
            g = 1 if a1 == 0 else 0 # REF->1, ALT->0
        geno_dict[samples[idx]].append(str(g))

vcf.close()
if n_loci == 0:
    sys.exit("[ERROR] 过滤后无多态 Y-SNP 位点，检查数据。")

print(f"[INFO] 采集到 {n_loci} 个多态位点，写入 {out_txt}")

# ---------- 4. 写 DIYABC TXT ----------
with open(out_txt, "w", encoding="utf-8") as f:
    f.write(f"{sex_ratio} {maf_tag}  Y-SNP data generated by script\n")
    f.write("IND SEX POP " + " ".join(["Y"] * n_loci) + "\n")
    for s in samples:
        pop = pop_map.get(s, "P1")  # 若没列出则默认 P1
        sex = "M"                   # Y-染色体 → 男性
        f.write(f"{s} {sex} {pop} " + " ".join(geno_dict[s]) + "\n")

print("[DONE] DIYABC 输入文件已生成。")
